### ISSUE TITLE
Documentation on web appears inconsistent with current stable release (2.10)

### ISSUE THREAD

**Issue by nrnrnr** [pandoc/lua-filters#109]
I've been using https://pandoc.org/lua-filters.html#pandoc.table as a guide to calling `pandoc.Table`.  But in the latest release (2.10), that interface is different.  The two should match.

It would be very helpful if the documentation on the web bore a version number.

**Comment by tarleb** [comment]
Relevant resources: 
- documentation: jgm/pandoc#6516
- proposed changes to make filter upgrades straight-forward: https://github.com/jgm/pandoc/pull/6575
- some background: https://groups.google.com/d/topic/pandoc-discuss/G60Sh0O0MLw/discussion

> It would be very helpful if the documentation on the web bore a version number.

It *should* always document the latest version (see also the linked issue above). 

Side note: I've been thinking about adding the pandoc version in which a feature was introduced. This would make the documentation more useful to users of older versions, who otherwise can't tell whether the documentation applies to them or not.

**Comment by jgm** [comment]
> Side note: I've been thinking about adding the pandoc version in which a feature was introduced. This would make the documentation more useful to users of older versions, who otherwise can't tell whether the documentation applies to them or not.

Good idea!

**Comment by tarleb** [comment]
This has been fixed, I think.
