### ISSUE TITLE
Integrate third party BBCode writers in pandoc upstream

### ISSUE THREAD

**Issue by wiki-me** [pandoc/lua-filters#186]
[This](https://github.com/lilydjwg/2bbcode) is the code in question 

I also opened an [issue]( https://github.com/lilydjwg/2bbcode/issues/5) with the third party repository mentioning why I think this is good for pandoc (besides making the writers more discoverable). 

Bbcode is very useful, if I want to write a long forum post I can write it in markdown or ODT (that have good editors), and then convert it to bbcode and then post it.

**Comment by ickc** [comment]
I think it is totally up to the author of the code to decide where they want to put it. If they want to submit a PR here, that's great. But else there's nothing we can do here, therefore it should be closing.

Also, some people might not want to submit it here because they want full control and maintain it themselves. Being "upstream" or not is no big deal, what's important is how well it is maintained.

Also, you could applied the same logic to every lua filter out there, since by definition every filter people wrote is at least very useful to someone. But we can't possibly ask everyone out there to migrate here instead. In some cases, people here just don't have the expertise to maintain things with 3rd party dependencies that we don't even use.

Lastly, just my opinion, a repo like this is useful when someone write something useful & maintainable, and yet they don't want to host their own for various reasons (opening a repo, creating their own testing framework, maintaining without help, long term commitment, etc.) If they already want to maintain it their own and spend the effort to setup all the things, it doesn't gain much to migrate here.

If on the other hand you're worried about their long term commitment, then it is no question either, wait until it is abandoned and forked it, possibly submitting a PR here if the license is compatible.
