### ISSUE TITLE
Filter table-short-captions produces invalid LaTeX

### ISSUE THREAD

**Issue by tarleb** [pandoc/lua-filters#48]
Trying to compile the provided sample file into a PDF gives an error due to `\undef` being an undefined control sequence.

    % pandoc -s --lua-filter table-short-captions.lua -F pandoc-crossref sample.md -o sample.pdf
    Error producing PDF.
    ! Undefined control sequence.
    l.163 \undef

@blake-riley, can you take a look?

**Comment by bpj** [comment]
May be a typo for `\relax`.

Den lör 30 mars 2019 15:32Albert Krewinkel <notifications@github.com> skrev:

**Comment by blake-riley** [comment]
Hi @tarleb,

**Background to the bug**
`\undef` is defined in the `etoolbox` package.
This isn't _explicitly_ loaded in the preamble of a pandoc-generated .tex file.
In pandoc .tex files, the `parskip` package is loaded _if possible_, and in turn it will load `etoolbox`.

**Why I missed the error**
I've got a _full_ installation of TeXLive 2018 running on my machine, so `parskip` gets loaded, which loads `etoolbox` in turn. This defines `\undef`, so everything runs smoothly.
I'm assuming that you don't have a full install of TeXLive, so it all falls apart because `parskip` isn't loaded.

**Fix options**
1. Just add a `\RequirePackage{etoolbox}`, and call it a day.
2. Avoid using `etoolbox` altogether. With `parskip` not available on your distribution, I am wary that `etoolbox` might also not be available.

Because (2) is a more robust solution, I went this way.
