### ISSUE TITLE
[wordcount] Feature request: Add character count

### ISSUE THREAD

**Issue by frederik-elwert** [pandoc/lua-filters#96]
When writing articles, sometimes there is a character limit instead of a word limit. Thus, it would be nice to have the wordcount filter additionally output the character count (probably with and without spaces).

**Comment by frederik-elwert** [comment]
I do have a patch available that does this for regular text. However, I am a bit uncertain how to approach the code part. (I personally don’t need it, but since the original filter also counts words in code, it would be desirable to do the same for the character count.) Especially when counting characters including spaces, this is tricky b/c of indentation. Should the character count ignore leading (and trailing) whitespace and only count spaces between characters?

If helpful, I could start a pull request with that I have, and maybe someone has ideas about the code-specific part?

**Comment by bpj** [comment]
I'm still to encounter a situation where counting the
non-blank UTF-8 grapheme clusters in Pandoc's plain
output doesn't give me a close enough estimate, so if you
have perl 5.14 or later installed just do this:

``````sh
pandoc -w plain input.md | perl -CADS -0777 -nE'say
scalar(@cc = /(?=\S)\X/g)'
``````

If you need to get an estimate which includes the 'actual'
blanks between words you can use a negative lookahead for
more than one blank instead of the positive lookahead for a
non-blank:

``````sh
pandoc -w plain input.md | perl -CADS -0777 -nE'say
scalar(@cc = /(?!\s{2})\X/g)'
``````

If you are worried about URLs in the text skewing the count
too much you can use a small Pandoc filter which replaces
links with their text and removes images:

``````lua
function Link (l) return l.content end
function Image () return {} end
``````

This removes captions as well, but since some characters
which don't count towards the effective character count are
counted it usually events out.
An alternative is to return the `content` for images too,
but this will include alt texts which aren't captions.
Do what works best in your case.

The kind of text where you are under character count
pressure rarely contain a lot of links so it kind of evens
out anyway.

If you want to count only the letter and number characters
you can use a positive lookahead for such
characters:

``````sh
pandoc -w plain input.md | perl -CADS -0777 -nE'say
scalar(@cc = /(?=[\pL\pN])\X/g)'
``````

Counting UTF-8 "words" can be done by changing this into a
pattern which matches sequences of "word"
characters:

``````sh
pandoc -w plain input.md | perl -CADS -0777 -nE'say
scalar(@wc = /(?:(?=[\pL\pN])\X)+/g)'
``````

Finally if the publisher are so stupid that they count
combining marks as separate characters just replace
`/(?=\S)\X/g` with `/\S/g` (and so on), possibly
`[\pL\pN]` with `[\pL\pN\pM]`.

However since in the real world publishers probably go
by the character/word count as shown by Word chances are
that converting to DOCX and see what counts Word or
LibreOffice gives is the most "reliable".

**Comment by frederik-elwert** [comment]
Sure, I *could* do all that in perl regex, but since there’s already the filter, I thought I could get around remembering/noting all those regexes and just do `pandoc --lua-filter wordcount.lua input.md` and be done. And I do have a version that works for my purposes, which I would be willing to share. But since it deviates from the original filter in handling code (which I do not need), I brought it up.

Thanks for listing all the regexes, though!

**Comment by jgm** [comment]
``` lua
-- counts words in a document

words = 0
chars = 0

wordcount = {
  Str = function(el)
    -- we don't count a word if it's entirely punctuation:
    local s = el.text:match("%P")
    if s then
        words = words + 1
        chars = chars + #s
    end
  end,

  Code = function(el)
    el.text:gsub("(%S+)",
      function(s)
        words = words + 1
        chars = chars + #s
      end)
  end,

  CodeBlock = function(el)
    el.text:gsub("(%S+)",
      function(s)
        words = words + 1
        chars = chars + #s
      end)
  end
}

function Pandoc(el)
    -- skip metadata, just count body:
    pandoc.walk_block(pandoc.Div(el.blocks), wordcount)
    print(words .. " words, " .. chars .. " characters in body")
    os.exit(0)
end
```
Tried this, but it didn't quite work (character count not accurate -- not sure why).

By the way, are you looking for a character count including spaces?

**Comment by frederik-elwert** [comment]
Here’s my current version:

```lua
-- counts words in a document 

words = 0 
characters = 0
characters_and_spaces = 0

wordcount = { 
  Str = function(el) 
    -- we don't count a word if it's entirely punctuation: 
    if el.text:match("%P") then 
        words = words + 1 
    end 
    characters = characters + utf8.len(el.text)
    characters_and_spaces = characters_and_spaces + utf8.len(el.text)
  end, 

  Space = function(el)
    characters_and_spaces = characters_and_spaces + 1
  end,

  Code = function(el) 
    _,n = el.text:gsub("%S+","") 
    words = words + n 
  end, 

  CodeBlock = function(el) 
    _,n = el.text:gsub("%S+","") 
    words = words + n 
  end 
} 

function Pandoc(el) 
    -- skip metadata, just count body: 
    pandoc.walk_block(pandoc.Div(el.blocks), wordcount) 
    print(words .. " words in body") 
    print(characters .. " characters in body") 
    print(characters_and_spaces .. " characters in body (including spaces)") 
    os.exit(0) 
end
```

I noticed that the string length in lua actually counts bytes, so it’s inaccurate with multi-byte characters. I used `utf8.len()` instead, which seems to work better.

I also need to get character count including spaces because this is often the relevant metric for publishers or other authorities.

My version just currently ignores code when determining the character count, because I was not sure about how to implement it, both technically and conceptually.

**Comment by bpj** [comment]
@frederik-elwert wrote:

>  ``````lua
>  Code = function(el) 
>    _,n = el.text:gsub("%S+","") 
>    words = words + n 
>  end, 
>  ``````

Maybe it's better to make the `gsub` nondestructive by using `"%0"` as the replacement, in case someone runs another filter after this one or actually saves the output.

>  
>  I noticed that the string length in lua actually counts bytes, so it’s inaccurate with multi-byte characters. I used utf8.len() instead, which seems to work better.

That's exactly why I have been preferring those Perl oneliners (the `-CADS` option turns on UTF-8 mode). I haven't been aware of `utf8.len` or at least it hadn't occurred to me that it could be used this way.

This is a very important improvement!

> My version just currently ignores code when determining the character count, because I was not sure about how to implement it, both technically and conceptually.

Why not just `utf8.len(code.text)`? It may overshoot the mark by counting more whitespace than there eventually will be in a DOCX file for example, but that's certainly better than a too low count.

**Comment by frederik-elwert** [comment]
> Maybe it's better to make the `gsub` nondestructive by using `"%0"` as the replacement, in case someone runs another filter after this one or actually saves the output.

But the result is only stored in a dummy variable `_`, so I guess it’s just discarded anyway and does not change the AST?

> Why not just `utf8.len(code.text)`? It may overshoot the mark by counting more whitespace than there eventually will be in a DOCX file for example, but that's certainly better than a too low count.

Right, I did that now.

I created a pull request, so maybe we can discuss remaining issues with the code there.

**Comment by jgm** [comment]
Thanks, I accepted the PR, but obviously if anyone has further comments about the proposal, feel free to speak up.
